---
- name: TESTING COMMANDS
  hosts: all
  gather_facts: false
  connection: local
  tasks:
  
- name: DISPLAYING THE RUNNING-CONFIG
  ios_command:
      commands:
      - show running-config
      - show version
      - show ip route
      register: run 

- name: SAVE OUTPUT TO ./tests/
  copy:
      dest: "tests/test_{{ inventory_hostname }}.txt"
      content:
        show running-config
        -----
        {{ run.stdout[0] }}
        show version
        -----
        {{ run.stdout[1] }}
        show ip route
        -----
        {{ run.stdout[2] }}