---
- name: here we go again
  hosts: csr1kv
  gather_facts: false
  connection: local

  tasks:
  - name: Ensure apache is at the latest version
    ios_command:
      commands:
        - show run
        - show ip route
        - show ip arp
    register: OUTPUT
  
  - name: SAVE
    debug:
      var: OUTPUT